### ISSUE TITLE
React Hook useEffect has a missing dependency:

### ISSUE THREAD

**Issue by Ajay-Dhangar** [adrianhajdin/project_fitness_app#21]
**Line 26:6:**
  React Hook useEffect has a missing dependency: 'setExercises'. Either include it or remove the dependency array. If 'setExercises' 
 changes too often, find the parent component that defines it and wrap that definition in useCallback  `react-hooks/exhaustive-deps`

<br>
------------------------------------------
<br>
**Request ** 

 _I Want your help, can you help me?_

 I don't know how to solve this issue can you support me for solving this warnings.

**Comment by Trex-Hub** [comment]
Hello, I Found a Fix to this error you have to modify the useEffect Hook in the Exercises.js component. You have to pass the setExercises in the Dependancy Error With bodyPart to avoid any Weird Behaviour. Here is the Solution for it 
Replace your useEffect Like This
```
  useEffect(() => {
    const fetchExercisesData = async () => {
      let exercisesData = [];

      if (bodyPart === 'all') {
        exercisesData = await fetchData('https://exercisedb.p.rapidapi.com/exercises', exerciseOptions);
      } else {
        exercisesData = await fetchData(`https://exercisedb.p.rapidapi.com/exercises/bodyPart/${bodyPart}`, exerciseOptions);
      }

      setExercises(exercisesData);

    };

    fetchExercisesData();
  }, [bodyPart, setExercises]);
 ```
 Hope It Helps
